name: Testing Rspec

on:
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Docker Compose v2
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
          docker compose version
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build services
        run: docker-compose build --no-cache

      - name: Start services
        run: docker-compose up -d

      - name: Run RSpec
        run: docker exec -e RAILS_ENV=test -e RACK_ENV=test roterize-api-web-1 bundle exec rspec