name: Testing Rspec

on:
  push:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yml"

      - name: Build images
        run: docker compose -f compose.yml build --no-cache

      # Start only dependencies (adjust names to match your compose)
      - name: Start dependencies
        run: docker compose -f compose.yml up

      # Run tests in a fresh, one-off container for your app service.
      # IMPORTANT: replace "web" with your actual service name in compose.yml
      - name: Run RSpec
        run: |
          docker compose -f compose.yml run --rm -T \
            -e RAILS_ENV=test -e RACK_ENV=test \
            web bundle exec rspec

      - name: Show logs on failure
        if: failure()
        run: docker compose -f compose.yml logs --no-color